config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:index, :show, :edit, :update]
  resources :playdates, only:[:index, :show, :new, :create, :edit, :update]

   namespace :api do
     namespace :v1 do
       resources :playdates, only: [:index, :show, :new, :create, :edit, :update, :destroy]
       resources :messages, only: [:create]
       resources :users, only: [:index, :show]
           get "users/current" => "users#current_user"
           # get "/meetups", to: "meetup#search"
     end
   end
   get "/meetups", to: "meetups#search"
   get "/meetups", to: "meetup#search"


  #  namespace :api do
  #   namespace :v1 do
  #     resources :messages, only: [:create]
  #     resources :users, only: [:show]
  #     get "users/current" => "users#current_user"
  #   end
  # end
end

app/models/Userdate.rb
class Userdate < ApplicationRecord
  belongs_to :user
  belongs_to :playdate 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages

end

app/models/event.rb
class Event < ApplicationRecord
  
end

app/models/meetup_parser.rb
require 'httparty'

class MeetupParser
  attr_reader :data

  def initialize
    @data = []
  end

  def search
    response = HTTParty.get()
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user


end

app/models/playdate.rb
class Playdate < ApplicationRecord
  validates :name, presence: true
  validates :time, presence: true
  validates :location, presence: true
  validates :description, presence: true

  has_many :userdates
  has_many :users, through: :userdates

  belongs_to :host, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_photo, ProfilePhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  available_days = ['Monday', 'Tuesday', 'Wendsday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :town, presence: true
  validates :age, presence: true
  validates :career, presence: true
  validates :availability, presence: true, inclusion: {in: available_days}

  has_many :userdates
  has_many :playdates, through: :userdates

  has_many :hosted_playdates, class_name: 'Playdate', foreign_key: 'host_id'

  has_many :messges

  def host?
    role == "host"
  end
end

app/controllers/api/v1/playdates_controller.rb
class Api::V1::PlaydatesController < ApplicationController

  def index
    render json: Playdate.all.order("created_at DESC")
  end

  def show
    playdate = Playdate.find(params[:id])
    users = playdate.users
    host = playdate.host
    render json: {playdate: playdate, host: host, users: users, currentUser: current_user}
  end

  def create
    playdate = Playdate.new(playdate_params)
    playdate.host = current_user
    if playdate.save
      render json: playdate
    else
      render json: { errors: playdate.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    playdate = Playdate.find(params[:id])

    if current_user == playdate.host
      if playdate.update(playdate_params)
        flash[:success] = "Playdate updated successfully"
        render json: playdate
      else
        render json: { errors: playdate.errors.full_messages }, status: :unprocessable_entity
      end
    else
      userdate = Userdate.new(user: current_user, playdate: playdate)
      record = Userdate.where(user: current_user, playdate: playdate).exists?
      
        if record
          users = playdate.users
          render json: {playdate: playdate, users: users,  error_message: "You have already attended this playdate"}
        else
          userdate.save
          playdate.save
          users = playdate.users
          render json: {playdate: playdate, users: users}
        end
      end
  end

  def destroy
    playdate = Playdate.find(params[:id])
    if current_user == playdate.host
      playdate.destroy
      render json: Playdate.all
    else
      render json: {playdate: "playdate", error_message: 'You are not authorized to delete this playdate!'}
    end
  end

  private
  def playdate_params
    params.require(:playdate).permit(:name, :location, :time, :description)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  def show
      render json: { user_id: current_user.id, first_name: current_user.first_name, profile_photo: current_user.profile_photo }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
     :age, :town, :career, :availability, :profile_photo])
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,
       :age, :town, :career, :availability, :profile_photo, :social_network, :number_of_kids,
       :born_month_and_year, :favorite_activities, :favorite_places])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/playdates_controller.rb
class PlaydatesController < ApplicationController
 #   before_action :authorize_user, except: [:index, :show]
 #
   def edit
     @playdate = Playdate.find(params[:id])
     binding.pry 
     unless current_user == @playdate.host
       redirect_to(@playdate, notice: "You cannot edit this playdate") and return
   end
   end
 #
 #
 #
 #
 #   def update
 #     @playdate = Playdate.find(params[:id])
 #
 #     if playdate.update(playdate_params)
 #       flash[:success] = "Playdate updated successfully"
 #       redirect_to: @playdate
 #     else
 #       render: edit
 #   end
 # end
 #
 #   def playdate_params
 #     params.require(:playdate).permit(:name, :location, :time, :description)
 #   end
 #
 #
 #   def authorize_user
 #     if !user_signed_in? || !current_user.host?
 #       flash[:notice] = "You do not have access to this page."
 #       redirect_to root_path
 #     end
 #   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     users = User.all
     @Users_without_current_users = array_without_current_user(users)
   end

  def show
    @user = User.find(params[:id])
  end

  private

  def array_without_current_user(users_array)
    new_array = users_array.select do |user|
      user != current_user
    end
    return new_array
  end

end

app/views/homes/index.html.erb
<div>
  <div class="home-orbit-container">
    <ul class="home-orbit" data-orbit>
      <li>
        <img src="/logo/carousel-1.jpg" />
      </li>
      <li>
        <img src="/logo/carousel-2.jpg" />
      </li>
      <li>
        <img src="/logo/carousel-3.jpg" />
      </li>
    </ul>
  </div>
  <div class="home-about">
    <div class="row">
      <div class="columns small-12 medium-6 large-4">
        <div class="card">
          <a href="/playdates">
            <div class="card-section">
              <h3>Find Local Playdates</h3>
            </div>
            <img src="/logo/card-1.jpg">
          </a>
          <div class="card-section">
            <p>
              Kids bored? Make a playdate for your kid to meet other kids.
              Either create your own or attend an existing playdate.
            </p>
          </div>
        </div>
      </div>
      <div class="columns small-12 medium-6 large-4">
        <div class="card">
          <a href="/users">
            <div class="card-section">
              <h3>Meet Other Parents</h3>
            </div>
            <img src="/logo/card-2.jpg">
          </a>
          <div class="card-section">
            <p>
              Looking to build friendships with other parents? Find other parents
              with similar interests and with kids the same age as yours.
            </p>
          </div>
        </div>
      </div>
      <div class="columns small-12 medium-6 large-4">
        <div class="card">
          <a href="/users/sign_up">
            <div class="card-section">
              <h3>Register Now</h3>
            </div>
            <img src="/logo/card-3.jpg">
          </a>
          <div class="card-section">
            <p>
              Create a profile today and get started meeting local parents and
              attending local playdates.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aikidsfun</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <div class="top-bar-contents">
      <span class="logo">
        <%= link_to image_tag("/logo/aikidsfun.png"), "/" %>
      </span>

      <section class="top-bar-section">
        <ul class="left">
          <li><%= link_to 'Playdates', playdates_path %></li>
          <li><%= link_to 'Parent Profiles', users_path %></li>
        </ul>
        <ul class="right">
          <%- if current_user -%>
            <li>
              <%= link_to edit_user_registration_path do %>
                <span class="profile-photo-nav">
                  <%= image_tag current_user.profile_photo.url.to_s %>
                </span>
                <span>Hi, <%= current_user.first_name %></span>
              <% end %>
            </li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </section>
    </div>

  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'

    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/playdates/edit.html.erb
<div id="app">

</div>

app/views/playdates/index.html.erb
<div id='app'>

</div>

app/views/playdates/new.html.erb
<div id="app">

</div>

app/views/playdates/show.html.erb
<div id="app">

</div>

app/views/users/index.html.erb
<h1>Parents</h1>
<% @Users_without_current_users.each do |user| %>
<div class='profile-box'>
  <div class="row">
    <div class='columns small-2 medium-3 large-2'>
    <span><%= image_tag user.profile_photo.url.to_s %></span>
    </div>

    <div class="columns small-10 medium-9 large-10">
          <div class="row">
            <div class="columns small-12">
              <%=link_to "#{user.first_name}  #{user.last_name}", user_path(user)%>
            </div>
          </div>

          <div class="row">
            <div class="columns small-12 tweet-content">
              Age: <%= user.age %>
            </div>
          </div>

          <div class="row">
            <div class="columns small-12 tweet-content">
              Job: <%= user.career %>
            </div>
          </div>

          <div class="row">
            <div class="columns small-12 tweet-content">
              Availability: <%= user.availability %>
            </div>
          </div>
    </div>
  </div>

</div>

<% end %>

app/views/users/show.html.erb
<h1>User Profile Show Page</h1>

  <div class="row">

    <div class='columns small-3 medium-3 large-3'>
    <span><%= image_tag @user.profile_photo.url.to_s %></span>
    </div>

    <div class='columns small-9 medium-9 large-9'>
        <div>
        <%= @user.first_name %> <%= @user.last_name %>
        </div>

        <div>
          Age: <%= @user.age %>
        </div>

        <div>
        Job: <%= @user.career %>
        </div>

        <div>
          Availability: <%= @user.availability %>
        </div>

        <div>
          Social Network: <%= link_to @user.social_network, url_for(@user.social_network) %>
        </div>
    </div>

  </div>

  <div class="row">

    <div class="
    question-list columns small-12 medium-12 large-12">
    <ol>
      <li>
        <div class="question">
          How many kids do you have?
        </div>
        <div class="answer">
          <%= @user.number_of_kids %>
        </div>
      </li>

      <li>
        <div class="question">
          What month and year was your child born?
        </div>
        <div class="answer">
          <%= @user.born_month_and_year %>
        </div>
      </li>

      <li>
        <div class="question">
          What kinds of activities does your kid like to do?
        </div>
        <div class="answer">
          <%= @user.favorite_activities %>
        </div>
      </li>

      <li>
        <div class="question">
          What places does your kid like to go?
        </div>
        <div class="answer">
          <%= @user.favorite_places %>
        </div>
      </li>
    </ol>

  </div>
</div>